# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.andrewriversidebjj.com
title: Andrew Riverside BJJ
email: 
author: Branden Bell
description: > # "Write an awesome description for your new site here. 
  Home Site for Andrew Riverside BJJ in Minneapolis Minnesota
copyright: 'Copyright &copy; 2020 David Soto. All Rights Reserved.'
credits: 'Credits: Branched from Landing Page Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/andrewriversidebjj/
  - title: facebook
    url: https://www.facebook.com/ARBJJCOLAB/
  